#!/usr/bin/perl
use utf8;
use strict;
use warnings;
use List::Util qw( reduce );

use v5.12;

my %patterns = (
  Gilligan   => qr/(?:Wiley )?Gilligan/,
  'Mary-Ann' => qr/Mary-Ann/,
  Ginger     => qr/Ginger/,
  Professor  => qr/(?:The )?Professor/,
  Skipper    => qr/Skipper/,
  'A Howell' => qr/Mrs?. Howell/,
);

say rightmost(
	'There is Mrs. Howell, Ginger, and Gilligan',
	\%patterns
);	
	
sub rightmost {
	my ( $string, $patterns ) = @_;

	return (
		reduce {
			my $b_idx = $string =~ m/$patterns->{$b}/ ? $-[0] : -1;
			$b_idx > $a->{idx} ? { name => $b, idx => $b_idx } : $a
		} { name => "None", idx => -1 }, sort keys %$patterns
	)->{name};
}
