#!/usr/bin/perl
use utf8;
use strict;
use warnings;

use v5.12;

my %patterns = (
  Gilligan   => qr/(?:Wiley )?Gilligan/,
  'Mary-Ann' => qr/Mary-Ann/,
  Ginger     => qr/Ginger/,
  Professor  => qr/(?:The )?Professor/,
  Skipper    => qr/Skipper/,
  'A Howell' => qr/Mrs?. Howell/,
);

say rightmost(
	'There is Mrs. Howell, Ginger, and Gilligan',
	\%patterns
);	
	
sub rightmost {
	my( $string, $patterns ) = @_;

	my @pats = @$patterns{ sort keys %$patterns };
	my $rightmost = -1;

	foreach my $pattern ( @pats ) {
		my $position = $string =~ m/$pattern/ ? $-[0] : -1;
		$rightmost = $position if $position > $rightmost;
	}

	return $rightmost;
}
