#!/usr/bin/env perl

use 5.014;
use warnings;
use Regexp::Assemble;

my $fname = $ARGV[0] // 'patterns.dat';
my $finish = $^O eq "MSWin32" ? "<Ctrl>+Z" : "<Ctrl>+D";

open my $file, $fname or die "Couldn't read $fname: $!\n";
my $regex = Regexp::Assemble->new->add( <$file> )->re;
close $file;

# LOL! Look at the regex this prints out for patterns.dat; can you spot the
# problem? We've rediscovered https://rt.cpan.org/Public/Bug/Display.html?id=74449

say "Resulting pattern";
say "-----------------";
say $regex;
say "\nNow type lines of text; $finish to finish.";

while ( <> ) {
	print "$.\t${^PREMATCH}<<<${^MATCH}>>>${^POSTMATCH}" while ( $_ =~ /$regex/g );
}
