#! /usr/bin/perl

use strict;
use Cwd;
use File::Basename;
use File::Spec;

sub magic_number_matches {
  return 0 unless -e '_build/magicnum';
  my $FH;
  open $FH, '<','_build/magicnum' or return 0;
  my $filenum = <$FH>;
  close $FH;
  return $filenum == 135584;
}

my $progname;
my $orig_dir;
BEGIN {
  $^W = 1;  # Use warnings
  $progname = basename($0);
  $orig_dir = Cwd::cwd();
  my $base_dir = '/home/dcox/workspace/int-perl/modules/dcox/Animal';
  if (!magic_number_matches()) {
    unless (chdir($base_dir)) {
      die ("Couldn't chdir($base_dir), aborting\n");
    }
    unless (magic_number_matches()) {
      die ("Configuration seems to be out of date, please re-run 'perl Build.PL' again.\n");
    }
  }
  unshift @INC,
    (
     '/home/dcox/perl5/lib/perl5/5.20.2/i586-linux-gnu-thread-multi-64int',
     '/home/dcox/perl5/lib/perl5/5.20.2',
     '/home/dcox/perl5/lib/perl5/i586-linux-gnu-thread-multi-64int',
     '/home/dcox/perl5/lib/perl5',
     '/home/dcox/perl5/lib/perl5/5.20.0'
    );
  push @INC, "." unless grep { $_ eq "." } @INC; # Force my process to include . in @INC.
  $ENV{"PERL_USE_UNSAFE_INC"} = 1; # Force all child processes to include . in @INC.
}

close(*DATA) unless eof(*DATA); # ensure no open handles to this script

use Module::Build;
Module::Build->VERSION(q{0});

# Some platforms have problems setting $^X in shebang contexts, fix it up here
$^X = Module::Build->find_perl_interpreter;

if (-e 'Build.PL' and not Module::Build->up_to_date('Build.PL', $progname)) {
   warn "Warning: Build.PL has been altered.  You may need to run 'perl Build.PL' again.\n";
}

# This should have just enough arguments to be able to bootstrap the rest.
my $build = Module::Build->resume (
  properties => {
    config_dir => '_build',
    orig_dir => $orig_dir,
  },
);

$build->dispatch;
