#!/usr/bin/env perl

use 5.014;
use warnings;

use local::lib;
use PeGS::PDF;

use constant {
	WIDTH => 3 * 72,
	HEIGHT => 6.5 * 72,
	XOFF => 10,
	YOFF => 3.75 * 72,
	YGAP => 20
};

my $pdf = PeGS::PDF->new({
	file => "ex01.pdf",
	'x'  => WIDTH,
	'y'  => HEIGHT,
});

die "Could not create object!" unless ref $pdf;

$pdf->make_reference( '$ginger', [ '', '', [ '', 'here' ] ], XOFF, HEIGHT - YGAP*2 );
$pdf->text( XOFF, YOFF, '$ginger->[2][1]' );
$pdf->text( XOFF, YOFF - YGAP, '$ginger->[2]->[1]' );
$pdf->text( XOFF, YOFF - YGAP*2, '${$ginger->[2]}[1]' );
$pdf->make_array( '@ginger', [ '', '', [ '', 'here' ] ], XOFF, YOFF - YGAP*5 );
$pdf->text( XOFF, YGAP, '${$ginger[2]}[1]' );

$pdf->close;
