#!/usr/bin/env perl

use 5.014;
use warnings;
use File::Slurp qw( read_dir );

my $dir = $ARGV[0] // '.';
dump_data_for_path( $dir, data_for_path( $dir ) );

sub data_for_path {
	my $path = shift;
	
	return undef if ( -f $path or -l $path ); # files or symbolic links
	return { map { $_ => data_for_path( "$path/$_" ) } grep /^[^.]/, ( read_dir $path ) } if ( -d $path );

	warn "$path is neither a file nor a directory\n";
	return undef;
}

sub dump_data_for_path {
	my ( $path, $data ) = @_;
	
	if ( not defined $data )  { # plain file
		print "$path\n";
		return;
	}

	foreach ( sort keys %$data ) {
		dump_data_for_path( "$path/$_", $data->{ $_ } );
	}
}
